update
chaoss/translations pull request #153
Opened 2022-09-20 07:10 UTC by sanglide

Signed-off-by: 171250022@smail.nju.edu.cn <171250022@smail.nju.edu.cn>

update the following files:

    https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/documentation-usability.md
    https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/issue-label-inclusivity.md
    https://github.com/chaoss/wg-dei/blob/main/focus-areas/project-and-community/documentation-discoverability.md

2022-09-20 12:50 UTC, eyehwan requested changes
There are some conflicts that need to be fixed. :)

2022-09-20 12:50 UTC, eyehwan commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
> +<<<<<<< HEAD:chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
There are some conflicts that need to be fixed. :)

2022-09-20 12:50 UTC, eyehwan commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
> +<<<<<<< HEAD:chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
There are some conflicts that need to be fixed. :)

2022-09-20 12:50 UTC, eyehwan commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
> +>>>>>>> 03c4446a6478ba5426b9fa2759bb523b411846b1:chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation_discoverability.md
There are some conflicts that need to be fixed. :)

2022-09-20 13:22 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
> +
added line breaks

2022-09-20 13:22 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
> +- 有些挑战
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
> +
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
> +- 有些挑战
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-discoverability.md
> +
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-usability.md
> +文档可用性是开源项目文档的一个关键方面，其在于确保不同用户都能理解开源项目的文档。文档可用性涵盖文档的结构、内容、术语和可读性，旨在推动最广大贡献者群体对项目的理解。
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-usability.md
> +* **技术术语** - 文档使用适当程度的技术术语，并提供必要的术语解释，确保特定项目的入门贡献者能够理解文档。
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-usability.md
> +* **可读性** - 文档语言应简洁明了，使用常用词和短句，以确保非母语者或可能不了解类似缩写惯例或推论模式的人能够理解。
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-usability.md
> +* **时间/注意力多元化** - 文档应该有包容性，能够让人们在不同时间读取或设置/运行命令。 还应考虑到需要照顾孩子或具有其他照护职责的人员，这些人员随时可能将注意力转移到屏幕之外。
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-usability.md
> +  * 描述一下您在社区工作中遇到问题时使用文档的经验。
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-usability.md
> +  * 采访后，社区可追踪回复，记为 `正面体验`、`负面体验` 或 `中性体验`，并逐月报告这些情况，了解随时间推移的改进情况。
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/documentation-usability.md
> +            并描述其在文档上遇到的问题。 这为文档编辑提供了具体用例，以了解如何针对具体用户改进文档。
make some translation changes

2022-09-20 13:26 UTC, sanglide commented on chinese/wg-diversity-inclusion/focus-areas/project-and-community/issue-label-inclusivity.md
> +*__新人友好__*：议题包括适当标注的议题（例如，“对新人友好的第一个议题”，“新人友好”），供新贡献者入门
make some translation changes

2022-09-21 08:46 UTC, eyehwan commented
Looks good to me. Thank you 👍  @sanglide

2022-09-21 08:46 UTC, eyehwan approved these changes

2022-09-21 08:46 UTC, merged